name: 01 - Hello

on:
  workflow_dispatch:

jobs:
  saludar:
    runs-on: ubuntu-24.04
    steps:
      - name: Saludar
        run: echo "Hola desde GitHub Actions!"

      - name: Mostrar la fecha
        run: date

      - name: Listar archivos
        run: ls -la

  repo-files:
    runs-on: ubuntu-24.04
    steps:
      - name: Descargar el código
        uses: actions/checkout@v6

      - name: Listar archivos
        run: ls -la
